### ISSUE TITLE
only can see search bar and cannot do anything else

### ISSUE THREAD

**Issue by 4Urban** [xcv58/Tab-Manager-v2#1012]
**Describe the bug**
When I click the button to open the tab manager, I can only see a search bar like below.
![image](https://user-images.githubusercontent.com/49590998/109996212-5ca46500-7d52-11eb-93b4-de468acdd4fa.png)

So I can only search other tabs or close those tabs unlike I could select some tabs and organize them before.
Even trying to cancel or exit that search bar through pressing `ESC` or click the button `X` on the right top corner is not working. Nothing change.

I hope what makes this error and can be solved soon.

Thank you!

**To Reproduce**
1. Just activate the app like click the button.

**Expected behavior**
Perform as a [screenshot](https://lh3.googleusercontent.com/EKWQoAf2a0mOCMA9L78uM8qJKRCCcQD6iysLFzhvaL3ommmDkWHYaQwK_UONQdPy9djf5E0sp6tkrdV1yYF6jW6v=w640-h400-e365-rj-sc0x00ffffff) on Web Store.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave 1.21.73  (Chromium: 89.0.4389.72 (64bit))
 - Version 1.14.2

**Comment by xcv58** [comment]
Hi @4Urban,

Thanks for reaching out, this is not a bug but on purpose. There are different ways to get the full view:

1. Use the shortcuts to open the extension in a popup window or a tab. 
  popup window: `Ctrl+t` for macOS, `Alt+t` for other systems.
  in a new tab: `Ctrl+o` for all systems.
  You can change the shortcuts in chrome://extensions/shortcuts
2. Click the open in new tab button on the top right:
![image](https://user-images.githubusercontent.com/503123/110031756-28965900-7cec-11eb-8e0f-f78d0d525ad3.png)

**Comment by 4Urban** [comment]
Oh, I see! I understood. Thank you!
