### ISSUE TITLE
Sessions Randomly Missing

### ISSUE THREAD

**Issue by DarkDullahan** [xcv58/Tab-Manager-v2#1339]
After over a year of continuous use with no issue on Microsoft Edge Chromium, I saved a tab session and noticed that I was on the "User Saved" filter category, but all of my prior saved sessions were missing. I attempted to reload the extension, and then restarted the browser when that failed to resolve the issue; but after those steps, it never did restore those sessions.

**Comment by xcv58** [comment]
Hi @DarkDullahan,

This extension never touches the sessions. It seems it's either another extension or builtin function controls your sessions.

**Comment by DarkDullahan** [comment]
Yeah, I apologize. I wasn't paying attention and went to the wrong extension's github and didn't realize that I'd made the mistake until after I'd typed the ticket up.  I haven't had too many issues otherwise. Apologies for clutter.
