### ISSUE TITLE
Integrate history URL search functionality to search bar 

### ISSUE THREAD

**Issue by zou000** [xcv58/Tab-Manager-v2#1399]
**Is your feature request related to a problem? Please describe.**
I usually have dozens of tabs open. Before opening a site,  I usually go to the tab manager to search if the site is already opened in a tab. However, if the site is not already opened, I'll have to re-type the search terms in the chrome address bar to open the site, possibly from chrome history.
 
**Describe the solution you'd like**
1. It would be great if the tab manager has something similar to the chrome address bar's history functionality, i.e. along with existing tabs, also bring up tab/url history that matches search terms. 
2. If the above idea is hard to implement, a simple alternative could be adding a button in the bookmark manager's search bar to copy search terms to the chrome address bar, saving the user from manually re-typing those terms.

**Comment by xcv58** [comment]
> It would be great if the tab manager has something similar to the chrome address bar's history functionality, i.e. along with existing tabs, also bring up tab/url history that matches search terms.

I have a similar idea. Let me try to implement this. I believe using this API is enough for the history  https://developer.chrome.com/docs/extensions/reference/history/#method-search

**Comment by xcv58** [comment]
Hi @zou000 ,

The feature is released via v1.16.0.

**Comment by zou000** [comment]
Thanks. It works perfectly for me after granting it history access.
