### ISSUE TITLE
Use a more brighter color for the icon

### ISSUE THREAD

**Issue by zou000** [xcv58/Tab-Manager-v2#1430]
**Describe the bug**
Use a more brighter color for the icon. Under a dark chrome theme, the icon is pretty hard to see.

<img width="57" alt="Screen Shot 2021-09-01 at 11 33 42 AM" src="https://user-images.githubusercontent.com/482689/131725124-a62c64b6-7154-47bd-9c75-cd775286eb06.png">

**Comment by xcv58** [comment]
Thanks for the feedback. I will investigate a possible solution.

**Comment by xcv58** [comment]
https://stackoverflow.com/a/58882519/2989263

**Comment by xcv58** [comment]
Fixed in 81d6423d62780fdfacede5b674d4db916be471f9
