### ISSUE TITLE
Redundant empty space in toolbar button window

### ISSUE THREAD

**Issue by silverwings15** [xcv58/Tab-Manager-v2#1683]
**Describe the bug**
Redundant empty space in toolbar button window

**To Reproduce**
1. Install Tab Manager 
2. Click on the toolbar button or press Alt-W or to bring up its window
3. There's a huge amount of empty space obscuring existing tabs that isn't present on the full-featured mode 

**Expected behavior**
There should be no empty space

**Screenshots**
![image](https://user-images.githubusercontent.com/10742312/148694204-fa01b614-3faf-4724-837e-e1d27d2378f9.png)
^ Toolbar window

![image](https://user-images.githubusercontent.com/10742312/148694205-c69dcce4-6b98-455d-8c7e-b7530de55350.png)
^ Full featured/standalone window (what it should look like)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome & Firefox
 - Version 1.18.3

Thank you for the otherwise stellar addon!

**Comment by xcv58** [comment]
Hi @silverwings15,

Thanks for the feedback. The extra space is the design of the Material UI Popper component. It try to leave some space to make the UI looks not so crowded. I will try to see whether we could decrease the extra space since it doesn't applicable for the use case here.

**Comment by silverwings15** [comment]
just got the new update and it looks much better now. thank you again for implementing my suggestion ❤️

**Comment by xcv58** [comment]
Great, thank you for your feedback and patience!
