### ISSUE TITLE
[Request] Support Chrome's Tab Grouping feature.

### ISSUE THREAD

**Issue by nakedpantsu** [xcv58/Tab-Manager-v2#1821]
Hi,

Is it possible for this extension to be able to manage tabs that are grouped (create, add, remove, etc)? Or at least be aware of Tab Groups and be able to color code tabs that are in the same group?

Thanks in advance!

**Comment by xcv58** [comment]
Thanks for reaching out. It should be doable since the api exists https://developer.chrome.com/docs/extensions/reference/tabGroups/

It should look like the Firefox container feature. https://github.com/xcv58/Tab-Manager-v2/issues/499

**Comment by nakedpantsu** [comment]
Oh cool! Thanks for this. Cheers!

**Comment by xcv58** [comment]
This feature is blocked by 

<img width="636" alt="image" src="https://user-images.githubusercontent.com/503123/158025397-2a4487c0-f475-44a5-8919-136966cc15d2.png">

https://github.com/xcv58/Tab-Manager-v2/issues/1207

**Comment by xcv58** [comment]
PR https://github.com/xcv58/Tab-Manager-v2/pull/1853

It looks like:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/503123/159198818-d4fbed78-afde-4cdc-a087-eec934ac9170.png">
