### ISSUE TITLE
Problem in floating window

### ISSUE THREAD

**Issue by Phreeshad** [xcv58/Tab-Manager-v2#1929]
I'm not sure if this is really a bug, but in my opinion the user expects to be able to navigate to the desired location with the **Enter key** or **clicking** on any item in the add-on **floating window**.
I don't understand why a user should have to open the extension in a new tab for such a function.
Is this a problem just about me?

**Comment by Phreeshad** [comment]
I found hotkeys and the trick was **Ctrl+Enter**!
It was a lot tricky to find that section,
Anyway, thank you for creating this life saver.

**Comment by Phreeshad** [comment]
The other thing I want to bring up is grouping, or just grouping visually based on some rule or even users custom grouping. This may be really a good option I'm looking for.
You might not be too bad to take a look at this [link](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/).

**Comment by xcv58** [comment]
What you describe is definitely a bug.

Can you provide a little more information so that I can reproduce it? Things like the below will help me a lot:

- Chrome (or other browser you used the extension) version, 
- Extension version (you can click the setting icon and scroll to bottom to find the version)
- OS name and version

It would be great if you can share any screenshots.

**Comment by Phreeshad** [comment]
> Can you provide a little more information ...
I use Manjaro KDE:
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.17.1-3-MANJARO (64-bit)
Graphics Platform: X11

**Comment by xcv58** [comment]
Gotcha, I can reproduce the same on Firefox. I will work on a fix in 1-2 days.

**Comment by Phreeshad** [comment]
> It would be great if you can share any screenshots.

https://user-images.githubusercontent.com/97948809/164120980-a4d3e74f-81e6-4663-a048-9e2f8a5f55af.mp4

**Comment by xcv58** [comment]
Can you double-check whether the v1.21.2 https://addons.mozilla.org/en-US/firefox/addon/tab-manager-v2/ fixes the problem for you?

**Comment by Phreeshad** [comment]
Yea, it's solved now. Good job man. I'll be back with more suggestions later...

**Comment by xcv58** [comment]
Great, please feel free to open new issues.
