### ISSUE TITLE
[Function Request] Toggle for Duplicate Tab Detection of Non-Case-Sensitive and Partial URL 

### ISSUE THREAD

**Issue by DarkDullahan** [xcv58/Tab-Manager-v2#2231]
A nice QOL functionality for those dealing with large tab lists with potential duplicate tabs would be a toggle or parameter functionality to allow detection of tabs with _visually identical_ URL that use different case text.

Additionally to that if feasible: 
Detecting if a Portion-of-Whole URL link is identical to another and displaying as a duplicate; such as the case of a URL being opened on one tab with a whole URL whilst another tab has that same web page open with additional variables and telemetry data following the main URL handle (see: Twitter links or sharing links via button on Amazon).

This would help out immensely with long-form lists of large quantities of tabs in a window.

**Comment by xcv58** [comment]
Hi @DarkDullahan ,

Not sure I understand your request correctly, so please correct if it's wrong.

Are you asking the `Highlight Duplicated Tabs` feature? 
![image](https://user-images.githubusercontent.com/503123/226214362-dabe5e77-4259-4317-b939-e0efd0c90e75.png)

If yes, we already have such feature and support to close all duplicated tabs (will keep one tab) by a shortcut or click:

![image](https://user-images.githubusercontent.com/503123/226214443-8bf6a365-7bf1-4f56-883a-52c1c32116eb.png)


![image](https://user-images.githubusercontent.com/503123/226214452-2b5df7e8-ceec-423b-b084-929c9009bccf.png)

**Comment by DarkDullahan** [comment]
I'm referring to specific functionality of it, or a lack thereof whenever a partial capitalization (case-sensitive) difference on an otherwise identical URL, the duplicate detection function is not able to detect that it is a duplicate URL potentially due to Unicode differences. 

Example:

![ss (2023-03-19 at 07 03 33)](https://user-images.githubusercontent.com/8221867/226215321-68ea4919-ce49-4146-b429-c0378b1bbfcf.png)


> "edition/9N4S0RKK24CQ" has 5 instances of its URL, 4 duplicates. Only one is detected as a duplicate.

- edition/9N4S0RKK24CQ
- edition/9n4s0RkK24cQ
- edition/9N4S0rkk24CQ
- edition/9N4S0RKK24cq

Each of the above are the same URL, however due to certain capitalizations being different, it does not determine them as the same.

- edition/9N4S0RKK24CQ/0017
- edition/9N4S0rkk24CQ/0017

The above two URL are also primarily what the other portion of my function request pertain to:
The ability to flag a tab with a URL that is [x]% identical to another as duplicate. 

This last one is less important than the prior issue but would have use for someone like me who can frequently manage quite a large number of tabs at once.

**Comment by xcv58** [comment]
Good point, the Non-Case-Sensitive fix is on the way.

![image](https://user-images.githubusercontent.com/503123/226220569-39a8043d-114a-46f6-974c-5a30cfbc1d63.png)


I will think about the Partial URL match case, and I will appreciate it if you can provide more examples.
