### ISSUE TITLE
Request to be able to rename tabs groups to something meaningful.

### ISSUE THREAD

**Issue by mikhoul** [xcv58/Tab-Manager-v2#232]
I've found your extension browsing for a tab managers/grouper and it Tab-Manager-v2 seem very good and simple at the same time, also it is very responsive.

But what I'd like is to be able to rename tabs groups to something meaningful than only the number of tabs in the header of the group.

Here's a quick mockup: 

![image](https://user-images.githubusercontent.com/5678673/46116337-9cea7b00-c1c9-11e8-8bbf-4c054d2e4bec.png)

If you need more informations just ask me.

Best Regards :octocat:

**Comment by xcv58** [comment]
To add a title is not hard. But it seems not very intuitive to manage. 

* You have to manually type the title. 
* The title will be lost if you accidentally close the window. 
* It's also a mess if you open some tabs not related to the current group.

Any idea for the above situations?

**Comment by mikhoul** [comment]
[**@xcv58**](https://github.com/xcv58) commented on [26 sept. 2018 à 23:34 UTC−4](https://github.com/xcv58/Tab-Manager-v2/issues/232#issuecomment-424947585 "2018-09-27T03:34:07Z - Replied by Github Reply Comments"):
> To add a title is not hard. But it seems not very intuitive to manage.
> 
> *   You have to manually type the title.

Only the first time we name it, after name should be saved in a DB and tagged to the tabs group until l the groupe is empty. 


> *   The title will be lost if you accidentally close the window.

Not if the name is saved in a DB and tagged to the tab group.

> *   It's also a mess if you open some tabs not related to the current group.

Not really because I keep all my session clean with name like "Programming project XYZ", Movies, Android Stuff, etc...   So when I work on a project I just open the right tab group. 😊

**Comment by dkapz** [comment]
I second this request! I was using Panorama View tab manager in Firefox and that allowed for naming of groups which was nice. It has a nice visual map of all windows and tabs you can pull up via hotkey as well. 

Thanks for your work on this - will keep an eye out for updates.

**Comment by xcv58** [comment]
I will try to implement this in https://github.com/xcv58/Tab-Manager-v2/issues/1821

**Comment by xcv58** [comment]
Will implement in #2352
