### ISSUE TITLE
Why is "Manage extensions and themes" permission requested?

### ISSUE THREAD

**Issue by rulatir** [xcv58/Tab-Manager-v2#2321]
Document the requested permissions and exactly how they are used. Why would this extension need to MANAGE other extensions and themes?

**Comment by xcv58** [comment]
It's used here https://github.com/xcv58/Tab-Manager-v2/blob/master/packages/extension/src/js/stores/Tab.tsx#L214

When you have other extensions that open tab(s), it requires permission to get their icon to show it. That's the only place this permission be used. 

However, chrome doesn't allow declare permission by this call only and thus we have to ask the "management" permission:
https://developer.chrome.com/docs/extensions/reference/management/#method-get
