### ISSUE TITLE
Chrome Canary setting blocking popup.js & background.js ?

### ISSUE THREAD

**Issue by Growflavor** [xcv58/Tab-Manager-v2#235]
An older version was working in both Chrome Canary as well as regular Chrome, but now I see the following errors in Chrome Canary (new version runs ok in Chrome)...perhaps a Canary setting is blocking the popup.js & background.js 

https://photos.app.goo.gl/jQekgsAmhN7nyEGx7

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome,canary  Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by xcv58** [comment]
I test this on macOS 10.14 (18A389) with Chrome Version 71.0.3569.0 (Official Build) canary (64-bit).

Can't reproduce the same issue. Could you please double check this still happen on Windows with Chrome 71?

**Comment by zaecas** [comment]
Having the same issue in Chrome Beta Version 70.0.3538.45 (Official Build) beta (64-bit)

![capture](https://user-images.githubusercontent.com/19718598/46574707-0d3d8d00-c97e-11e8-86c8-1986d067a82b.JPG)
![capture2](https://user-images.githubusercontent.com/19718598/46574708-0d3d8d00-c97e-11e8-8f1a-4668af14c976.JPG)

**Comment by xcv58** [comment]
@zaecas thanks for sharing this.
I'll find a Windows to test it.

**Comment by kevin01523** [comment]
i also experienced this on a new chrome beta install i have 2 diff windows pc same chrome beta version but the other pc tab manager v2 works but on the new install of chrome it doesnt work errors and symptoms the same provided by zaecas

**Comment by kevin01523** [comment]
![image](https://user-images.githubusercontent.com/8380242/47187178-b5cbf380-d365-11e8-82c5-2f53757bb643.png)

**Comment by xcv58** [comment]
I use Windows 10 Home with Chrome versions:
* Version 70.0.3538.67 (Official Build) (64-bit)
* Version 70.0.3538.67 (Official Build) beta (64-bit)
* Version 71.0.3578.10 (Official Build) dev (64-bit)
* Version 72.0.3584.0 (Official Build) canary (64-bit)

can't reproduce the same issue.

I did reproduce the issue on Windows 10 Education English with VirtualBox. Could you please provide more details about the OS versions?

**Comment by xcv58** [comment]
I publish a new version v0.18.2 which work on my VirtualBox. Could you please confirm whether it works on your machine?


https://chrome.google.com/webstore/detail/tab-manager-v2/nimllkpgmmbdglnjneeakdgcpkbgbfbp

**Comment by kevin01523** [comment]
it works now but font seems too big?
![image](https://user-images.githubusercontent.com/8380242/47230970-435b2200-d3fe-11e8-8cb7-350a4ddc2b2f.png)

**Comment by kevin01523** [comment]
still throws errors cant enable dark theme and no options on the bottom
![image](https://user-images.githubusercontent.com/8380242/47231752-6555a400-d400-11e8-8ba5-30e0d3616284.png)


![image](https://user-images.githubusercontent.com/8380242/47231801-86b69000-d400-11e8-8e44-891583722c9e.png)

**Comment by xcv58** [comment]
Thanks for your feedback @kevin01523 

The v0.18.2 is just a temporary fix and I still don't know the root cause of the bug. And my VirtualBox is too slow to debug. I'll figure out whether there is another way can tackle the bug.

**Comment by kevin01523** [comment]
its not on the os im sure i have 2 chrome on my windows pc and just have 2 diff profiles the problem occurs on the new chrome install w/ new google chrome profile and still works fine on the old one same version i did sync it from my old chrome install

**Comment by xcv58** [comment]
Could you double check whether it's the latest extension version. You can find it via chrome://extensions or right click the icon and select `Manage Extensions`.

**Comment by kevin01523** [comment]
yeah its the latest i tried both the unpacked version(github release zip) and from the chrome store

**Comment by zaecas** [comment]
Yihong,
It's working again for me! Still the same OS version, but now on Chrome Version 70.0.3538.67 (Official Build) beta (64-bit). 

Thanks!

**Comment by kevin01523** [comment]
![image](https://user-images.githubusercontent.com/8380242/47258856-2e50c280-d4d4-11e8-878e-389643dd5529.png)
but options below still missing

**Comment by xcv58** [comment]
Thanks @kevin01523 @zaecas 

The theme and toolbar/options missing issue is the same https://github.com/KeithHenry/chromeExtensionAsync/issues/10 

And I double check it works on below versions:
Version 70.0.3538.67 (Official Build) (64-bit)
Version 72.0.3587.0 (Official Build) canary (64-bit)

does **NOT** work on the **beta** and **dev** versions:
Version 70.0.3538.67 (Official Build) beta (64-bit)
Version 71.0.3578.10 (Official Build) dev (64-bit)


I think it's bug on chromium side and since it works on canary. My assumption is the functionality will work eventually after beta and dev merge upstream canary code.

**Comment by Growflavor** [comment]
Thanks all for following up while I was away :-) & yes, it has been working nicely again since 72...
