### ISSUE TITLE
Synchronise with Google account

### ISSUE THREAD

**Issue by jetownfeve21** [xcv58/Tab-Manager-v2#246]
**Is your feature request related to a problem? Please describe.**
I work mainly  on Linux but I switch sometimes on windows but tabmanager is not synchronised with google account so tabmanager is empty on my windows side.

**Describe the solution you'd like**
An authentification should solve that for example with google account, I don't know if it's possible.

**Comment by xcv58** [comment]
Can you share a screenshot on Windows side?

**Comment by jetownfeve21** [comment]
This is on Linux's side :

![image](https://user-images.githubusercontent.com/47149116/56414290-6de14700-628a-11e9-8360-ca0f1600340b.png)

**Comment by jetownfeve21** [comment]
This is on windows side : 

![image](https://user-images.githubusercontent.com/47149116/56414460-e0522700-628a-11e9-993c-d56c79b13238.png)

**Comment by xcv58** [comment]
Sorry @jetownfeve21  this repo is for the Tab Manager v2: 
https://chrome.google.com/webstore/detail/tab-manager-v2/nimllkpgmmbdglnjneeakdgcpkbgbfbp
