### ISSUE TITLE
ctrl + t shortcut gets hijacked

### ISSUE THREAD

**Issue by jadami-stripe** [xcv58/Tab-Manager-v2#2469]
**Describe the bug**
`ctrl + t` opens this the tab manager window. But that shortcut is also used in places like go/llm for new thread. As far as I can tell, there's no way to modify the shortcuts.

**To Reproduce**
1. go to go/llm
2. press `ctrl + t`
3. tab manager opens

**Expected behavior**
I have a way to remap opening to something not `ctrl + t`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version Version 120.0.6099.71 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yihong-stripe** [comment]
Hi @jadami-stripe,

Sorry I missed the email. You can change the default `ctrl + t` shortcut in chrome by visiting chrome://extensions/shortcuts
