### ISSUE TITLE
Middle mouse click on tab to close it?

### ISSUE THREAD

**Issue by mxmilkiib** [xcv58/Tab-Manager-v2#2474]
This is the behaviour for general tabs.

**Comment by xcv58** [comment]
Fixed in https://github.com/xcv58/Tab-Manager-v2/pull/2477

**Comment by xcv58** [comment]
1.25.1 published https://chromewebstore.google.com/detail/tab-manager-v2/nimllkpgmmbdglnjneeakdgcpkbgbfbp
