### ISSUE TITLE
Opening via the keyboard (Alt-T) doesn't work in Firefox

### ISSUE THREAD

**Issue by keithbowes** [xcv58/Tab-Manager-v2#259]
When I try it in Firefox (both the latest ESR and Nightly), I get the following error in the Browser Console:
Error: Type error for parameter createData (Property "focused" is unsupported by Firefox) for windows.create.

Perhaps, you could use a try...catch and call without any properties in case it fails.

**Comment by xcv58** [comment]
Thanks @keithbowes for reporting this. It should be fixed in v0.19.8 https://addons.mozilla.org/en-US/firefox/addon/tab-manager-v2/
