### ISSUE TITLE
Opening a tab from within the extension doesn't work in Firefox

### ISSUE THREAD

**Issue by keithbowes** [xcv58/Tab-Manager-v2#260]
It doesn't matter if I use the keyboard or the mouse, I see a few flashes as if it's loading and the following in the Browser console, but the extension doesn't switch to the tab:
Error: Type error for parameter updateProperties (Property "selected" is unsupported by Firefox) for tabs.update.

**Comment by xcv58** [comment]
Thanks @keithbowes for reporting this. It should be fixed in v0.19.8 https://addons.mozilla.org/en-US/firefox/addon/tab-manager-v2/

**Comment by xcv58** [comment]
Fixed in v0.19.8
