### ISSUE TITLE
"Auto Focus Search Box" option doesn't work

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#275]
When I click add-on button and popup opens then search box is NOT in focus, I start typing but search box stays empty.  
Tried turning on/off  "Preserve search" but it result is the same.

 - OS: Windows 7  64bit
 - Firefox 68.0.1 64bit (firefox portable)
 - Tab Manager v2   0.21.3

![Image 2019-08-09 17-41-32 001](https://user-images.githubusercontent.com/53944324/62787337-2a2a7b80-bacd-11e9-9fc4-a4844c42e0a0.png)

**Comment by xcv58** [comment]
Thanks for reporting this. I confirmed this on macOS as well. It's a bug during a past framework upgrade.
I'll fix this soon.

**Comment by xcv58** [comment]
This should be fixed in v0.21.4. Could you please take a look?

**Comment by mike-tn** [comment]
Yes, it works OK now. Thank you very much!

P.S. Also it looks to me that popup window now takes more time to open (about .7-1 sec) than it took in prev version. Do you see the same, or is it only on my PC?

**Comment by xcv58** [comment]
I'm not aware of any load time change. But I made a change to solve potential performance issue in v0.21.5.

**Comment by mike-tn** [comment]
It seems a little bit faster.

**Comment by xcv58** [comment]
Thanks for confirming
