### ISSUE TITLE
[New Feature] Clear Search Box button

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#277]
In addition to Esc key, please add a button to clear the search box.

Lets say I have the addon open in separate window and have some tabs filtered out. When I just want to clear filter to brows all tabs without new search,  it would be nice to be able to do it without keyboard.

**Comment by xcv58** [comment]
A good suggestion, I appreciated it and will add this feature soon.

**Comment by xcv58** [comment]
This feature should be added in v0.21.4. Could you please take a look?

![image](https://user-images.githubusercontent.com/503123/62817421-1f7edf00-baeb-11e9-8072-0b7a07ef6ca0.png)

**Comment by mike-tn** [comment]
NO, I  updated but don't have this button  ( whenever search box is in focus or not)  neither   in popup, nor in separate window!


![Image 2019-08-10 17-15-09 001](https://user-images.githubusercontent.com/53944324/62822889-7c81a000-bb92-11e9-9137-6e32d7970d14.png)

**Comment by xcv58** [comment]
I have no idea why it doesn't show up for you. Could you please try this to see whether it has close button:

https://codesandbox.io/s/silent-frog-lk2ml

**Comment by mike-tn** [comment]
I opened the link and see this

![Image 2019-08-10 20-24-35 001](https://user-images.githubusercontent.com/53944324/62824991-4bfb2f80-bbad-11e9-8c04-74c60ab80376.png)

I clicked Open in New Window and got to this

![Image 2019-08-10 20-24-21 001](https://user-images.githubusercontent.com/53944324/62824997-67fed100-bbad-11e9-9702-5cbc070ad4a0.png)

What should I do exactly?

**Comment by xcv58** [comment]
Sorry for the inconvenience. I made a full deploy. Could you please check the link?
![image](https://user-images.githubusercontent.com/503123/62828033-42fc6500-bb91-11e9-8c84-f34d88d72201.png)

It should have only an input box and close icon when you hover or focus on the input.

https://csb-lk2ml.netlify.com

**Comment by mike-tn** [comment]
No close icon
That's what I get:
![Image 2019-08-11 20-10-12 001](https://user-images.githubusercontent.com/53944324/62837164-ea05fd00-bc74-11e9-88b9-73d617fffaed.png)

![Image 2019-08-11 20-10-44 001](https://user-images.githubusercontent.com/53944324/62837171-fbe7a000-bc74-11e9-8980-c551f7083522.png)

![Image 2019-08-11 20-11-14 001](https://user-images.githubusercontent.com/53944324/62837176-01dd8100-bc75-11e9-96b4-404807b08f7b.png)

![Image 2019-08-11 20-11-28 001](https://user-images.githubusercontent.com/53944324/62837177-06a23500-bc75-11e9-93ed-e1e663fb3154.png)

**Comment by xcv58** [comment]
Thank you so much for checking this. I'll figure out another way to make it compatible with your environment.

**Comment by xcv58** [comment]
![image](https://user-images.githubusercontent.com/503123/62838393-4266db80-bc30-11e9-9638-301f42e2d1f8.png)
It should be fixed in v0.21.6

**Comment by xcv58** [comment]
![image](https://user-images.githubusercontent.com/503123/62838398-514d8e00-bc30-11e9-939e-e7a3ab4d4baa.png)

**Comment by mike-tn** [comment]
Yes, it works! 
Thanks a lot!
