### ISSUE TITLE
When moving to search box with "/" key, select all the content of search box.

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#278]
One more idea about search box:

Now when I move to the box with "/" key then, if it  has some characters in it, cursor moves to after last char.
I think it would be better in such cases to select all the content of search box (see below), so if I  want to replace old search string with new I just start typing new chars, but if I want to add something to old string I press right arrow and type additional chars.

![Image 2019-08-12 12-13-06 001](https://user-images.githubusercontent.com/53944324/62855311-98a05100-bcfa-11e9-956f-8eaccfa051aa.png)

**Comment by xcv58** [comment]
Thanks @mike-tn 
I have considered this but the same strategy can be applied:

> so if I want to replace old search string with new I press Command/Ctrl+A and type the new chars.

> but if I want to add something to old string I just start typing.

**Comment by mike-tn** [comment]
ОК, Ctrl+A will go.

Thanks for a tip!
