### ISSUE TITLE
Lose focus of search box during typing

### ISSUE THREAD

**Issue by xcv58** [xcv58/Tab-Manager-v2#282]
**Describe the bug**
Lose focus of search box during typing.

**To Reproduce**
1. Open multiple windows with different tabs.
2. Open the extension view and make sure autofocus search is off
3. Use keyboard to focus on a tab
4. Search other tabs which make the tab focus state change (ideally another window)
5. It would lose focus state for the search box

**Expected behavior**
It should not lose focus state for the search box

**Screenshots**
N/A

**Additional context**
N/A

**Comment by xcv58** [comment]
This bug caused by this line: https://github.com/xcv58/Tab-Manager-v2/commit/9f9158665dfaf2c1e26614fd186cedbee486b5eb#diff-720856473aa9db4b53f70bae0f07aba1R65

In a webpage, when an element gets focus, other elements would lose their focus. So if the search causes focus change, the `buttonRef.current.focus()` will move focus on the tab content element, which leads to search box loses focus.

The fix is here: 2195efc85dfcb247b23812bb762cb5c345189789
It uses an opposite idea to solve the stale focus issue by blur the tab content when it loses focus.

**Comment by mike-tn** [comment]
Have the same bug!

    OS: Windows 7 PRO 64b
    Browser: Firefox 69.0 (64b)
    Version: Tab Manager v2 0.21.9

**Comment by xcv58** [comment]
It should be fixed by v0.21.10, please verify you have the latest version?

**Comment by xcv58** [comment]
It seems the Firefox publish pipeline is broken. I will fix it.

**Comment by mike-tn** [comment]
works Ok now.

Thanks!!!
