### ISSUE TITLE
Select all tabs opened in a specified container

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#287]
I often open tabs in containers (use Firefox Multi-Account Containers and Temporary containers add-ons). Sometimes I need to see all tabs open in a particular container or to see are  there any tabs open in the container. 

Firefox Multi-Account Containers  allows  to see all tabs in a chosen container only in the current window. When I have several windows it becomes a problem.

So it would be a very useful feature in Tab Manager v2 to select all tabs for a specified container (e.g. chosen from a dropdown list of containers)! Then I can move them all to a new window ... etc.

Filter on container  can be combined with filter on a search string.

**Comment by xcv58** [comment]
Do you mean this extension? https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

If yes, my initial investigation shows the feature is not doable. Because the container is maintained by the Multi-Account Containers adds on, the Tab Manager v2 can't get the information for the container.

**Comment by mike-tn** [comment]
Containers are maintained by Firefox, many add-ons deal with them.

You don't even need  the  Multi-Account Containers add-on - if you install Tree Style Tab add-on (or some others) then  containers become accessible via long-click on the "Open a new tab" button in the Firefox tabs bar.

Tab's property "tab.cookieStoreId" is a container id. 
Example  of a function creating new tab in the same container of a current tab (from  https://github.com/jonathanKingston/new-container-tab ):

async function createContainerTab() {
  const tabs = await browser.tabs.query({
    currentWindow: true,
    active: true
  });
  const tab = tabs[0];
  browser.tabs.create({
    index: tab.index + 1,
    cookieStoreId: tab.cookieStoreId
  });

Container names are  in %FirefoxProfileFolder%containers.json  (userContextId the same as   cookieStoreId). I never  dealt with list of conteiners,  it's described  in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_contextual_identities

**Comment by xcv58** [comment]
Interesting, I don't know this before, will take a look to see whether it's feasible.

**Comment by xcv58** [comment]
Hi @mike-tn 

I started to add minimal container support in https://github.com/xcv58/Tab-Manager-v2/issues/499
Currently, it shows the container indicator only.

And I will add more features like you request, and potential features like group tabs by containers, etc. 


A preview of my pending work:
![image](https://user-images.githubusercontent.com/503123/83959549-f629ff00-a832-11ea-8abc-a538681db9d1.png)

**Comment by xcv58** [comment]
The select tabs in a container is released in https://github.com/xcv58/Tab-Manager-v2/blob/master/CHANGELOG.md#1131-2020-06-09

https://addons.mozilla.org/en-US/firefox/addon/tab-manager-v2/
