### ISSUE TITLE
Bottom toolbar prevents from clicking on the horizontal scrollbar

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#288]
When the option Always show toolbar in settings is on, bottom toolbar overlaps horizontal scrollbar and when clicking on the scrollbar the buttons of the toolbar are clicked instead.

It happens when open in a popup and in a separate window.

**Screenshots**
At screenshot moment the cursor was on the scrollbar under the "Close focused tab" button.

![Image 2019-09-18 13-39-20 001](https://user-images.githubusercontent.com/53944324/65142645-d5f3af00-da1b-11e9-832a-99259a5c632e.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 PRO 64b
 - Browser: Firefox 69.0 (64b)
 - Version: Tab Manager v2   0.21.9

**Comment by xcv58** [comment]
A workaround is disable `Always Show Toolbar`.

Currently, I don't have a good idea about how to solve this.
