### ISSUE TITLE
Can I disable closing tabs with Backspace?

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#289]
Can I somehow disable closing tabs with Backspace?

I usually open extension in a separate window.  I often accidentally close tabs when deleting symbols with backspace in the search bar or in the firefox' search box.

**Comment by xcv58** [comment]
Sure, I have the same issue before but mostly caused by #282.

**Comment by xcv58** [comment]
Remove the backspace to close tab on `v0.21.13`
