### ISSUE TITLE
The custom scroll bar doesn't work on firefox

### ISSUE THREAD

**Issue by xcv58** [xcv58/Tab-Manager-v2#308]
We may need the postcss https://github.com/postcss/postcss-loader

**Comment by xcv58** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

> ::-webkit-scrollbar is only available in WebKit-based browsers (e.g., Safari, all browsers on iOS, and others).

**Comment by hackel** [comment]
@xcv58 I was going to report this as a separate issue, but I assume it's related.  I'm not seeing *any* scrollbar on Firefox with 1.5.2.  The only way to scroll is with j/k.

**Comment by xcv58** [comment]
Weird, it works for me but only scrolling:

![image](https://user-images.githubusercontent.com/503123/76660927-5876aa80-6537-11ea-8773-b841e7d177ff.png)

**Comment by xcv58** [comment]
My Firefox is 74.0 (64-bit)
macOS 10.15.2
