### ISSUE TITLE
[Bug] Scrollbars disappeared. Horizontal scrolling now impossible.

### ISSUE THREAD

**Issue by mike-tn** [xcv58/Tab-Manager-v2#358]
In last versions of the extension scrollbars disappeared. Horizontal scrolling now impossible.

Open popup window. When I hover mouse near window borders there are no scrollbars. I can scroll vertically  using  mouse, but can't scroll horizontally.
 
In old versions there were scrollbars.

Desktop
 - OS: Windows 7 PRO SP1 64bit
 - Browser : Firefox 72.0.2  64bit 
 - Version : Tab Manager v2  1.8.0.

**Comment by xcv58** [comment]
Thanks for reporting. I will try to reproduce it on Firefox.

**Comment by xcv58** [comment]
I can't reproduce on my laptop:

![image](https://user-images.githubusercontent.com/503123/78816138-23b71100-7986-11ea-8b41-e1d244b61768.png)

![image](https://user-images.githubusercontent.com/503123/78816121-20238a00-7986-11ea-901d-f8f0ad3d24e9.png)

![image](https://user-images.githubusercontent.com/503123/78816249-552fdc80-7986-11ea-9154-abf713b36aba.png)

- OS: macOS 10.15.4
- Browser: Firefox 75.0 (64-bit)
- Version : Tab Manager v2 1.8.0


Could you please upgrade Firefox and try again? And share a screenshot if possible?

**Comment by mike-tn** [comment]
Upgraded to Firefox 75.0. I see the same.
Screenshots:


![Image 2020-04-09 14-08-44 001](https://user-images.githubusercontent.com/53944324/78895933-517c8280-7a78-11ea-80c4-b66153417caa.png)

   
![Image 2020-04-09 14-07-52 001](https://user-images.githubusercontent.com/53944324/78895962-5d684480-7a78-11ea-9ee4-58d2881560a6.png)

![Image 2020-04-09 13-58-33 001](https://user-images.githubusercontent.com/53944324/78895971-61946200-7a78-11ea-8fc0-f742190b1a8b.png)


 OS: Windows 7 PRO SP1 64bit
    Browser : Firefox 75.0 64bit
    Version : Tab Manager v2 1.8.0.

**Comment by xcv58** [comment]
@mike-tn I'll try to reproduce this in a Windows VM.

**Comment by xcv58** [comment]
[build.zip](https://github.com/xcv58/Tab-Manager-v2/files/4460042/build.zip)

I'll test this build on WIndows.

**Comment by xcv58** [comment]
Finally works 
![image](https://user-images.githubusercontent.com/503123/78969817-c2de2480-7abc-11ea-898e-30b7a1c4bf64.png)

**Comment by xcv58** [comment]
The v1.8.1 should fix the problem @mike-tn 

There is another issue: I can't use the trackpad to scroll horizontally. I don't know whether this applies to your machine.

But anyway, I'll work on #370 to replace the library causes the issue.

**Comment by mike-tn** [comment]
Yes, 1.8.1 works fine!!!
