### ISSUE TITLE
Popup just a command bar

### ISSUE THREAD

**Issue by liubog2008** [xcv58/Tab-Manager-v2#546]
I hope to use a shortcut to open Popup which just contains a `command bar` -- like mac alfred or spotlight

**Comment by liubog2008** [comment]
My hopeful use flow:

1. open the command bar
2. type to search
3. open the selected tab or a new one
4. archive the opened tabs

**Comment by xcv58** [comment]
Can you clarify what's the meaning of: `archive the opened tabs`?

**Comment by liubog2008** [comment]
suspend and store it for search in the future

**Comment by xcv58** [comment]
Thanks for your clarification. To suspend and store tabs is not the primary goal for this extension. There are ton of other extensions can do this.

**Comment by xcv58** [comment]
There is an implementation in:https://github.com/xcv58/Tab-Manager-v2/blob/master/packages/extension/CHANGELOG.md#features
