### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by schweini** [xcv58/Tab-Manager-v2#599]
Is there a way to open the Tab Manager v2 UI with a keyboard shortcut?

I'd like to be able to switch to other tabs using purely the keyboard.

At least in the docs, I couldn't find any mention of a keyboard shortcut.

**Comment by xcv58** [comment]
Yes, there are shortcuts and you can config it.

To open the standalone popup: Ctrl+T (macOS), Alt+T (other systems).

To config them on Chrome: chrome://extensions/shortcuts


There are more defined here:
https://github.com/xcv58/Tab-Manager-v2/blob/master/src/manifest.json#L20

I'll update the readme to include more usage information.

**Comment by schweini** [comment]
Thanks! I was actually looking for the "Activate the extension" shortcut, which wasn't set by default.
Works exactly like I want it to now! :-)
